### ISSUE TITLE
What's the current state of this project?

### ISSUE THREAD

**Issue by tevino** [curator-go/curator#1]
Found this project via https://github.com/flier/curator.go/issues/5

I'm interested in cache recipe, is this project production-ready?

**Comment by basvanbeek** [comment]
I would not label production ready although parts of this library are used in production.

The cache recipes have not been used by me nor does the repository have proper tests for them. If interested why not try out the cache recipes and maybe help out with a PR for a cache recipe unit test.

**Comment by tevino** [comment]
Except recipes is it feature complete beside Java's curator?

**Comment by basvanbeek** [comment]
Probably not so I urge you to inspect the existing code base to see if you find something missing...

I moved the existing undocumented project over and fixed what I needed for my use case and that is used in production... I'm willing to help keep it alive and happily accept PR's but have no time to build this library out with items I don't personally need at the moment. 

If looking for a polished curator ready library for Go, this one will be the closest to it. Feel free to document, help, maintain, etc. If that is not sufficient and have no time or interest to get stuff ready then I suggest abandoning the idea of using curator style access to ZooKeeper from Go.

**Comment by tevino** [comment]
I'll try this first, hopefully a PR someday.

Thanks for your patient reply. 😋
