### ISSUE TITLE
Get data from NodeCache?

### ISSUE THREAD

**Issue by bpodgursky** [curator-go/curator#6]
Hi, let me know if there's a better place for this question (I didn't see a mailing list)

I'm looking into using the NodeCache recipe, but I'm having trouble figuring out how to actually get the data out of the node.  The Java Curator NodeCache has a  getCurrentData() method, and I'm trying to figure out what the equivalent is here.

I understand the recipes here are only somewhat finished, so I'm happy to add a a getter if necessary.  Just want to make sure I'm not missing something obvious.

**Comment by basvanbeek** [comment]
@tevino can you chime in?

**Comment by bpodgursky** [comment]
To update, I've switched to a TreeCache for now and it's working fine for now, but I'm still curious if I was misunderstanding NodeCache.

**Comment by tevino** [comment]
[The NodeCache](https://github.com/curator-go/curator/blob/master/recipes/cache/node_cache.go) was extracted from [the old code]( https://github.com/curator-go/curator/blob/8d823988f8a51ebb5eb11008610e0f6c62aaf647/recipes/cache.go#L80) without much touch.

@bpodgursky I guess it is not mean to be used separately, for the absence of data getter, you could add one if you want.

**Comment by bpodgursky** [comment]
Thanks @tevino.  I'm just using the TreeCache with depth=0 and data caching instead for now.  Hopefully isn't much of a performance hit.  If I run into issues I might take a look at exposing more methods on the NodeCache.
