### ISSUE TITLE
Links to leader, cache, locking and discovery examples are broken

### ISSUE THREAD

**Issue by elifkus** [curator-go/curator#7]
The links leader, cache, locking and discovery under Examples on the README page (https://github.com/curator-go/curator) are broken. 

Where can I find the example for 'discovery' ?

And if you tell me what the new links are I can fix them.

**Comment by basvanbeek** [comment]
The project was never finished and these examples do not exist. 

At the moment nobody is actively working on this package. It remains here simply for somebody to move it forward or for people that successfully deployed the existing code and want it available to be able to pull in the dependency as is.

**Comment by elifkus** [comment]
Ok, thank you.
